UPSTREAM: <carry>: Update ArifactView enum to allow pipelines artifacts api to have optional content disposition
opendatahub-io/data-science-pipelines pull request #118
Opened 2024-11-15 01:33 UTC by VaniHaripriya

**Description of your changes:**

- This PR improves the Pipelines Artifacts API by adding flexible URL options for artifact retrieval. 
- It introduces a new RENDER field to the enum, which, when selected, provides a signed URL without the content disposition header. 
- This allows for the immediate download of artifacts in some cases, while also enabling preview or rendering in other scenarios.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2024-11-15 01:34 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 3 commits between e27b68731776c35efe5e363295c3cc4a782cec4f...6e694366abc04d1d8dc8d8f9bdda52a4ee03d626

UPSTREAM commit 6e69436 has invalid summary Update signedurl.

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w.-]+/[\w-.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert



UPSTREAM commit 156c4dd has invalid summary Updated swagger.

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w.-]+/[\w-.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert



UPSTREAM commit 17bcd01 has invalid summary Update ArifactView enum to allow pipelines artifacts api to have optional content disposition.

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w.-]+/[\w-.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert


```

2024-11-15 01:36 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
ERROR: couldn't find commits from e27b68731776c35efe5e363295c3cc4a782cec4f..f80f8616d30bb5c8a8b4c57ad40b271e6cc68474: error executing git log: fatal: Invalid revision range e27b68731776c35efe5e363295c3cc4a782cec4f..f80f8616d30bb5c8a8b4c57ad40b271e6cc68474
: exit status 128
```

2024-11-15 01:37 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 1 commits between e27b68731776c35efe5e363295c3cc4a782cec4f...74d1b1fa1c21319f01228d4d1d274bf02c512bf6

UPSTREAM commit 74d1b1f has invalid summary Update ArifactView enum to allow pipelines artifacts api to have optional content disposition.

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w.-]+/[\w-.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert


```

2024-11-15 01:44 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
ERROR: couldn't find commits from e27b68731776c35efe5e363295c3cc4a782cec4f..c4e69f8162abb6610ac403ddae389c39fb16c91c: error executing git log: fatal: Invalid revision range e27b68731776c35efe5e363295c3cc4a782cec4f..c4e69f8162abb6610ac403ddae389c39fb16c91c
: exit status 128
```

2024-11-15 01:44 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 1 commits between e27b68731776c35efe5e363295c3cc4a782cec4f...35108eeaac314fbb9fe9d638a0b73c32bd783168

UPSTREAM commit 35108ee has invalid summary Update ArifactView enum to allow pipelines artifacts api to have optional content disposition.

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w.-]+/[\w-.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert


```

2024-11-15 01:47 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 1 commits between e27b68731776c35efe5e363295c3cc4a782cec4f...a2234bab86edf454157be9792259893332f652c6
```

2024-11-19 19:37 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
ERROR: couldn't find commits from 7c3b0204f09934458ccd7ce65deba74fb0146286..e2464055788506a67239dccf68007fd136d3db94: error executing git log: fatal: Invalid revision range 7c3b0204f09934458ccd7ce65deba74fb0146286..e2464055788506a67239dccf68007fd136d3db94
: exit status 128
```

2024-11-19 19:38 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...560543daaba6fb73564d7279b900297e2d0a1021
```

2024-11-19 19:46 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 19:47 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 19:50 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...b2c1022b258a74014b0ddd7090b523b7a857dd46
```

2024-11-19 20:00 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 20:04 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...97287e36caa59dff93ce33e9d3db95e10bb840eb
```

2024-11-19 20:14 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...f3877f42021bca317f6d808be8e5f66c398b7918
```

2024-11-19 20:14 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 20:22 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 20:29 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...37e68e1aebe6d498d7ce7243a69606d9f68c6457
```

2024-11-19 20:39 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-19 20:52 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...1385dcea9c4b63bd3c10a7623f904a3098e17c54
```

2024-11-19 21:02 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-22 18:33 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...0570a6ab6bb21dc7f016b72c7ba514b5c25eebfc
```

2024-11-22 18:44 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-22 18:58 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...03a51c2b958f4d06b79f8b8c19d28085e0a4a086
```

2024-11-22 19:11 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-22 20:11 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...2e5fc933a13e1693ddc895ec3b85ad82da00c02a
```

2024-11-22 20:21 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-11-25 17:14 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...41d686438f32792521c59da19f49477f587ead84
```

2024-11-25 17:23 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2024-12-03 19:00 UTC, hbelmiro commented
@VaniHaripriya both URLs took me to the very same screen. Is that the expected result?

<img width="1840" alt="Screenshot 2024-12-03 at 15 59 14" src="https://github.com/user-attachments/assets/ce157154-4445-46d0-be21-5b623980915a">

2024-12-03 19:13 UTC, hbelmiro reviewed
/lgtm

as long as https://github.com/opendatahub-io/data-science-pipelines/pull/118#issuecomment-2515356519 is the expected result.

2024-12-03 19:15 UTC, hbelmiro commented
/hold for https://github.com/opendatahub-io/data-science-pipelines/pull/118#issuecomment-2515356519

2024-12-03 21:50 UTC, hbelmiro commented
/unhold
I was probably taking too much time to open the URLs.
I re-tested on a different browser and it works as expected.

2025-01-09 20:20 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +	GetSignedUrlWithoutContentDisposition(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string) (string, error)
Could we make this more configurable? For example, the following would allow further customizations without having to add a new method for each variation.
```suggestion
	GetSignedUrlWithQueryParams(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string, queryParams url.Values) 
```

2025-01-09 20:26 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +	reqParams.Set("response-content-disposition", "attachment; filename=\""+key+"\"")
If you go with my comment of having the method `GetSignedUrlWithQueryParams(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string, queryParams url.Values) `, then you can just have `GetSignedUrl` wrap `GetSignedUrlWithQueryParams` and pass the content disposition to `queryParams`.

This will reduce code duplication.

2025-01-09 20:29 UTC, mprahl commented on backend/src/apiserver/server/artifact_server.go
> +	includeRenderUrl bool,
Optional, but rather than a bool, you could replace `includeShareUrl` and `includeRenderUrl` with a single argument of type `GetArtifactRequest_ArtifactView` since it doesn't seem like this will ever need to generate more than one. This would allow for additional options in the future.

2025-01-09 20:33 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +func (m *MinioObjectStore) GetSignedUrlWithoutContentDisposition(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string) (string, error) {
What's the plan for test coverage of this method since the tests I see are mocking this out? Is this a separate task for an integration test?

2025-02-10 20:17 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-10 22:37 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-11 14:26 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +	GetSignedUrlWithoutContentDisposition(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string) (string, error)
This method isn't needed anymore since you can just call `GetSignedUrlWithQueryParams` with the correct content disposition header provided as a query parameter.

2025-02-19 23:10 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-19 23:44 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-19 23:45 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 02:36 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +func (m *MinioObjectStore) GetSignedUrlWithQueryParams(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string, queryParams url.Values) (string, error) {
Could you make `GetSignedURL` call this method with empty queryParams so we don't duplicate code?

2025-02-20 03:38 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 03:39 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 04:00 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 04:01 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 04:51 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 04:58 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 04:59 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 05:08 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 05:12 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 17:04 UTC, rimolive requested changes
I tested for `?view=RENDER` case and it looks good. However, for `?view=DOWNLOAD` case I could not see the expected behavior. I marked the place that it's missing the code. Let me know if you need a help.

2025-02-20 17:04 UTC, rimolive commented on backend/src/apiserver/server/artifact_server.go
> +		queryParams := make(url.Values)
According to the requirement, this block should have a line like this:
```
queryParams.Set("response-content-disposition", "attachment")
```

2025-02-20 21:01 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-20 21:03 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-24 13:54 UTC, rimolive commented
/lgtm

Tested with iris-pipeline, and when `view=DOWNLOAD` is passed to the artifact uri I get the `download_url` link, that redirects me to the download dialog. While `view=RENDER` just redirects me to a page to preview the artifact.

2025-02-24 14:24 UTC, mprahl commented on backend/src/apiserver/resource/resource_manager.go
> +func (r *ResourceManager) GetSignedUrlWithQueryParams(bucketConfig *objectstore.Config, secret *corev1.Secret, expirySeconds time.Duration, artifactURI string, queryParams url.Values) (string, error)
Sorry, my previous comment was about keeping `GetSignedURL` and having it call `GetSignedUrlWithQueryParams` to reduce code duplication, so that we don't make an not backwards compatible API change since this is a method on the interface.

That being said, since this API isn't upstream and nothing depends on it, I'm okay with this change. We should just change the name to be `GetSignedUrl` though.

2025-02-24 14:26 UTC, mprahl commented on backend/src/apiserver/storage/object_store.go
> +	GetSignedUrlWithQueryParams(bucketConfig *objectstore.Config, secret *v1.Secret, expirySeconds time.Duration, artifactURI string, queryParams url.Values) (string, error)
Same comment as above. Since we are going with a not backwards compatible change here, we might as well keep the name `GetSignedUrl`.

2025-02-24 19:48 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-24 19:49 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-118`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-118`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-118`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-118`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-118`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-118`

2025-02-24 20:46 UTC, mprahl approved these changes

2025-02-24 20:46 UTC, mprahl commented
/approve
/lgtm

2025-02-24 20:49 UTC, merged