UPSTREAM: <carry>: Reworded logs to indicate non-critical issues and …
opendatahub-io/data-science-pipelines pull request #67
Opened 2024-07-31 19:19 UTC by VaniHaripriya

Resolves [RHOAIENG-6710](https://issues.redhat.com/browse/RHOAIENG-6710)

Updated some log messages in DSP server to clearly convey that the reported issues are non-critical and intended for informational purposes only, helping users understand that these messages do not require immediate action.

2024-07-31 19:20 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 1 commits between bbfb5897533403b38ad8956424931868c103b0b0...332712fbb95e9b69bad2b40bc72d28c85866f179
```

2024-07-31 19:28 UTC, dsp-developers commented
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-67`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-67`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-67`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-67`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-67`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-67`

2024-07-31 19:28 UTC, dsp-developers commented
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-67.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-67
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-67"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-67"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-67"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-67"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-67"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/mlmd-grpc-server:latest"
    envoy:
      image: "registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-67"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/67/head
git checkout -b pullrequest 332712fbb95e9b69bad2b40bc72d28c85866f179
oc apply -f dspa.pr-67.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

2024-08-01 11:16 UTC, amadhusu commented on backend/src/apiserver/main.go
> +		glog.Fatalf("Failed to load samples.This can be safely ignored if sample configurations are not needed. Err: %v", err)
Isn't the Fatalf function here going to exit either way with `os.Exit(2)` so basically it can't be ignored? Same question applies for line 108.

2024-08-13 13:58 UTC, gregsheremeta requested changes

2024-08-13 13:58 UTC, gregsheremeta commented on backend/src/apiserver/client/swf.go
> +	glog.Infof("Non-critical error: Failed to create scheduled workflow client by out of cluster kubeconfig. This can be safely ignored if running in-cluster.Error: %v", err)
I would just delete this line. I don't see the point of it.

2024-08-13 13:58 UTC, gregsheremeta commented on backend/src/apiserver/main.go
> +		glog.Fatalf("Failed to load samples.This can be safely ignored if sample configurations are not needed. Err: %v", err)
```suggestion
		glog.Infof("Couldn't load optional pipeline samples: %v", err)
```

2024-08-13 13:58 UTC, gregsheremeta commented on backend/src/apiserver/main.go
> +			glog.Fatalf("Failed to create default experiment.This can be safely ignored if the default experiment is not needed. Err: %v", err)
```suggestion
			glog.Infof("Couldn't create optional default experiment: %v", err)
```

2024-08-13 17:53 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between d0ee4ca4524ece9f201581345ef791a1d4ee8e68...0374852ea62b5cc8b0d99a4b38aef4fc362970d5
```

2024-08-13 18:03 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-67`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-67`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-67`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-67`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-67`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-67`

2024-08-13 18:29 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between d0ee4ca4524ece9f201581345ef791a1d4ee8e68...250cff4fe6071260f6cce944c842a5de4a739308
```

2024-08-13 18:31 UTC, gregsheremeta commented
lgtm but can you squash these before we merge it?

2024-08-13 18:32 UTC, gregsheremeta commented
/lgtm
/approve

thanks!

2024-08-13 18:32 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between d0ee4ca4524ece9f201581345ef791a1d4ee8e68...3fe68376ce94d1ca7354d68bae7d530a899b7b1c
```

2024-08-13 18:35 UTC, merged

2024-08-13 18:36 UTC, dsp-developers commented
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between a8fbbd2020d280f4cab31245a9639a350207b3f9...3fe68376ce94d1ca7354d68bae7d530a899b7b1c
```

2024-08-13 18:38 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-67`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-67`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-67`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-67`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-67`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-67`

2024-08-13 18:41 UTC, dsp-developers commented
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-67`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-67`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-67`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-67`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-67`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-67`